---
- name: Ensure packages needed for mariadb are present
  apt: name={{ item }} state=present
  with_items:
    - mariadb-client
    - php5-mysqlnd
- name: Create mariadb DB for the Wordpress project
  mysql_db: "name={{ wordpress_dbname }} state=present"
- name: Create mariadb user for the Wordpress project
  mysql_user: 
    name: "{{ wordpress_dbuser }}"
    password: "{{ wordpress_password }}"
    priv: "{{ wordpress_dbname }}.*:ALL"
    state: present
  register: mariadb_user_result

