---
- name: Ensure packages needed for WP running under nginx+php-fpm are present
  apt: name={{ item }} state=present
  with_items:
    - php-gd
    - php-imagick
    - ssl-cert # needed for snakeoil nginx config

- name: Create config for wordpress site
  template:
    src: nginx.conf
    dest: "/etc/nginx/snippets/php-fpm-{{ wordpress_base_name }}.wordpress.conf"
  notify: nginx restart

