---
- name: Ensure packages needed for WP running under nginx+php-fpm are present
  apt: name={{ item }} state=latest
  with_items:
    - nginx
    - php5-fpm
    - php5-gd
    - php5-imagick
- name: Delete default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: nginx restart
- name: Create config for wordpress site
  template: "src=nginx.conf dest=/etc/nginx/sites-enabled/{{ wordpress_base_name }}.conf"
  notify: nginx restart

