---
- name: Ensure sync target folder exists
  file:
    path: "{{ sync_base_target }}"
    state: directory
- name: Sync local src
  synchronize:
    src: "{{ item }}"
    dest: "{{ sync_base_target }}"
    archive: no
    recursive: yes
    checksum: yes
    rsync_path: sudo rsync
  with_items: sync_paths
- name: Fix synced src's permissions
  file:
    path: "{{ sync_base_target }}"
    state: directory
    owner: "{{ wordpress_user }}"
    group: www-data
    recurse: yes
    mode: "u=rwX,g=rX,o=" # X != x, remember

