---
- name: apt-get update/upgrade
  apt: update_cache=yes upgrade=yes cache_valid_time=3600

- name: Ensure packages needed for basic Wordpress provisioning are present
  apt: name={{ item }} state=present
  with_items:
    - rsync
    - php-cli
    - wordpress

- name: Ensure that wordpress_user exists
  user:
    name: "{{ wordpress_user }}"
    createhome: no
    shell: /bin/bash
    # We need to be able to read-write uploads written by php-fpm
    groups: www-data

