---
- name: Get wordpress version
  shell: "wp --path={{ wordpress_site_root }} core version"
  register: wpcli_core_version
  ignore_errors: yes
  changed_when: no
  become: yes
  become_user: "{{ wordpress_user }}"
- name: Download wordpress core
  shell: "wp core download --path={{ wordpress_site_root }} --version={{ wordpress_core_version }} --locale=fr_FR"
  when: wpcli_core_version|failed
  become: yes
  become_user: "{{ wordpress_user }}"
- name: Update wordpress core
  shell: "wp core update --version={{ wordpress_core_version }}"
  args:
    chdir: "{{ wordpress_site_root }}"
  when: wpcli_core_version | success and wpcli_core_version.stdout | version_compare(wordpress_core_version, '<')
  become: yes
  become_user: "{{ wordpress_user }}"
