---
- name: Is Wordpress configured?
  stat: "path={{ wordpress_site_root }}/wp-config.php"
  register: wpconfig_stat
- name: Generate wp-config-extra.php
  template: "src=wp-config-extra.php dest={{ wordpress_site_root }}/wp-config-extra.php"
  become: yes
  become_user: "{{ wordpress_user }}"
- name: Create wp-config.php
  shell: >
    wp core config
    --dbname={{ wordpress_dbname }}
    --dbuser={{ wordpress_user }}
    --dbpass={{ wordpress_password }}
    --extra-php="require_once(dirname(__FILE__) . '/wp-config-extra.php');"
  args:
    chdir: "{{ wordpress_site_root }}"
  when: not wpconfig_stat.stat.exists
  become: yes
  become_user: "{{ wordpress_user }}"

