- name: Ensure that Wordpress' important dirs exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ wordpress_user }}"
    group: www-data
    mode: "2750" # leading 2 = setguid for the folder to propagate www-data group
  with_items:
    - "{{ wordpress_project_root }}"
    - "{{ wordpress_content_root }}"
    - "{{ wordpress_content_root }}/uploads"

- name: symlink the languages dir from the system's wordpress
  file:
    path: "{{ wordpress_content_root }}/languages"
    state: link
    src: /usr/share/wordpress/wp-content/languages

- name: Sync local themes
  include_tasks: srcsync.yml
  vars:
    sync_base_target: "{{ wordpress_content_root }}/themes"
    sync_paths: "{{ wordpress_local_themes }}"

- name: Sync local plugins
  include_tasks: srcsync.yml
  vars:
    sync_base_target: "{{ wordpress_content_root }}/plugins"
    sync_paths: "{{ wordpress_local_plugins }}"

- import_tasks: wordpress_config.yml

- name: Get current siteurl
  shell: "wp {{ wpcli_args }} option get siteurl"
  register: wordpress_siteurl_result
  ignore_errors: yes
  changed_when: no
  become: yes
  become_user: "{{ wordpress_user }}"

- name: Change siteurl if needed
  shell: "wp {{ wpcli_args }} option set siteurl \"{{ wordpress_url }}\" && wp search-replace \"{{ wordpress_siteurl_result.stdout.strip() }}\" \"{{ wordpress_url }}\""
  ignore_errors: yes
  when: "wordpress_siteurl_result.stdout.strip() != wordpress_url"
  become: yes
  become_user: "{{ wordpress_user }}"

- name: Install Wordpress public plugins
  shell: "wp {{ wpcli_args }} plugin install {{ item }}"
  args:
    creates: "{{ wordpress_content_root }}/plugins/{{ item }}"
  ignore_errors: yes
  with_items: "{{ wordpress_plugins }}"
  become: yes
  become_user: "{{ wordpress_user }}"

